volumes:
  sqlserver_data:


services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sa123456
    ports:
      - 1400:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
  web:
    restart: on-failure
    image: go-score
    ports:
      - 8080:8080
      - 8081:8081
# http://localhost:8080/swagger/index.html
# https://localhost:8081/swagger/index.html
# Passw0rd#