import type { Metadata } from "next";
import { Cairo } from "next/font/google"
import dynamic from "next/dynamic";
import Header from "@/app/pages/homePage/header/page"
// const Header = dynamic(() => import("@/app/pages/homePage/header/page"), {
//   ssr: true,
//   loading: () => <div className="h-16 border-b"></div>,
// });
import Footer from "@/app/pages/homePage/footer/page" 
// const Footer = dynamic(() => import("@/app/pages/homePage/footer/page"), {
//   ssr: true,
//   loading: () => <div className="h-40 bg-primary"></div>,
// });
import "./globals.css";

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  display: "swap",
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={`${cairo.variable}`}>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body className=" bg-background  font-cairo antialiased">
<Header />

        {children}
        
<Footer />
      </body>
    </html>
  );
}
